server:
  port: 8083
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/payments_db}
    username: ${SPRING_DATASOURCE_USERNAME:app_payment_user_db}
    password: ${SPRING_DATASOURCE_PASSWORD:Admin-Payment%123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    com.rafaelgalvezg.payment: INFO